name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      - name: Display unit test results
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: 'Unit tests: Results'
          report_paths: '**/build/test-results/testDebugUnitTest/TEST-*.xml'
